// creating an array of JSON objects containing the players' details

const players=[
    {name: "S. KERR", team:"https://media.contentapi.ea.com/content/dam/ea/fifa/fifa-23/ratings/womens-ratings/common/team-logo/116010.png", nationality:"https://media.contentapi.ea.com/content/dam/ea/fifa/fifa-21/ratings-collective/f20assets/country-flags/195.png", jerseyNumber:"", age:30 ,image:"https://media.contentapi.ea.com/content/dam/ea/fifa/fifa-23/ratings/common/womens-ratings/headshots/227125.png", position:'ST', rating:91 ,speed:87 , shooting:91 , passing:74 , dribbling:90 , defense:42 , physique:83 },
    {name: "A. MORGAN", team:"https://media.contentapi.ea.com/content/dam/ea/fifa/fifa-23/ratings/womens-ratings/common/team-logo/116312.png", nationality:"https://media.contentapi.ea.com/content/dam/ea/fifa/fifa-21/ratings-collective/f20assets/country-flags/95.png", jerseyNumber:"", age:34 ,image:"https://media.contentapi.ea.com/content/dam/ea/fifa/fifa-23/ratings/common/womens-ratings/headshots/226301.png", position:'ST', rating:90 ,speed:89 , shooting:91 , passing:80 , dribbling:88 , defense:47 , physique:77 },
    {name: "W. RENARD", team:"https://media.contentapi.ea.com/content/dam/ea/fifa/fifa-23/ratings/womens-ratings/common/team-logo/116033.png", nationality:"https://media.contentapi.ea.com/content/dam/ea/fifa/fifa-21/ratings-collective/f20assets/country-flags/18.png", jerseyNumber:"", age:33 ,image:"https://media.contentapi.ea.com/content/dam/ea/fifa/fifa-23/ratings/common/womens-ratings/headshots/227316.png", position:'CB', rating:90 ,speed:62 , shooting:72 , passing:71 , dribbling:71 , defense:93 , physique:87 },
    {name: "A. HEGERBERG", team:"https://media.contentapi.ea.com/content/dam/ea/fifa/fifa-23/ratings/womens-ratings/common/team-logo/116033.png", nationality:"https://media.contentapi.ea.com/content/dam/ea/fifa/fifa-21/ratings-collective/f20assets/country-flags/36.png", jerseyNumber:"", age:28 ,image:"https://media.contentapi.ea.com/content/dam/ea/fifa/fifa-23/ratings/common/womens-ratings/headshots/227310.png", position:'ST', rating:90 ,speed:83 , shooting:91 , passing:77 , dribbling:87 , defense:39 , physique:77 },
    {name: "L. BRONZE", team:"https://media.contentapi.ea.com/content/dam/ea/fifa/fifa-23/ratings/womens-ratings/common/team-logo/113002.png", nationality:"https://media.contentapi.ea.com/content/dam/ea/fifa/fifa-21/ratings-collective/f20assets/country-flags/14.png", jerseyNumber:"", age:32 ,image:"https://media.contentapi.ea.com/content/dam/ea/fifa/fifa-23/ratings/common/womens-ratings/headshots/227246.png", position:'RB', rating:89 ,speed:85 , shooting:77 , passing:82 , dribbling:83 , defense:88 , physique:87 }

]

export default players